/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.poly.duan1.ViewNV;

import edu.poly.duan1.view.*;
import edu.poly.duan1.model.ChucVu;
import edu.poly.duan1.services.ChucVuService;
import edu.poly.duan1.services.impl.ChucVuServiceImpl;
import edu.poly.duan1.ultis.helper;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Tien
 */
public class ViewNV_ChucVu extends javax.swing.JFrame {

    /**
     * Creates new form ViewNV_ChucVu
     */
    private ChucVuService chucVuu = new ChucVuServiceImpl();
    private DefaultTableModel tblModel;
    private helper helper = new helper();
    private SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    private List<ChucVu> cv;
    private List<ChucVu> cv2;
    private int sotrang = 1;

    public ViewNV_ChucVu() {
        initComponents();
        setLocationRelativeTo(null);
        cv = chucVuu.getAll();
        int heso = (sotrang * 5) - 5;
        cv2 = chucVuu.getAll2(heso);
        fillToTable(cv2);
//        fillToTable();
        uppanel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblchucvu = new javax.swing.JTable();
        txtsearch = new edu.poly.duan1.swing.textfield.TextField();
        jPanel1 = new javax.swing.JPanel();
        btnfirst = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        lblsotrang = new javax.swing.JLabel();
        btnnext = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Quản Lý Chức Vụ");

        tblchucvu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Ma", "Tên", "Ngày Tạo", "Ngày Sửa ", "Trạng Thái"
            }
        ));
        tblchucvu.setSelectionBackground(new java.awt.Color(38, 117, 191));
        tblchucvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblchucvuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblchucvu);

        txtsearch.setBackground(java.awt.SystemColor.control);
        txtsearch.setActionCommand("<Not Set>");
        txtsearch.setCaretColor(new java.awt.Color(255, 255, 255));
        txtsearch.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtsearch.setLabelText("Tìm Kiếm");
        txtsearch.setSelectedTextColor(new java.awt.Color(76, 204, 255));
        txtsearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtsearchCaretUpdate(evt);
            }
        });
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnfirst.setText("First");
        btnfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        lblsotrang.setText("label");

        btnnext.setText("Next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnlast.setText("Last");
        btnlast.setToolTipText("");
        btnlast.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnfirst)
                .addGap(18, 18, 18)
                .addComponent(btnback)
                .addGap(19, 19, 19)
                .addComponent(lblsotrang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnnext)
                .addGap(28, 28, 28)
                .addComponent(btnlast)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnback, btnfirst, btnlast, btnnext});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblsotrang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnfirst)
                        .addComponent(btnlast)
                        .addComponent(btnnext)
                        .addComponent(btnback)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnback, btnfirst, btnlast, btnnext});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtsearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
                        .addContainerGap(17, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblchucvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblchucvuMouseClicked


    }//GEN-LAST:event_tblchucvuMouseClicked

    private void txtsearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtsearchCaretUpdate
        search();
    }//GEN-LAST:event_txtsearchCaretUpdate

    private void btnfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstActionPerformed
        cv2.removeAll(cv2);
        sotrang = 1;
        int heso = (sotrang * 5) - 5;
        cv2 = chucVuu.getAll2(heso);
        fillToTable(cv2);
        uppanel();
    }//GEN-LAST:event_btnfirstActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        int tongSoTrang = cv.size() / 5;
        if (cv.size() % 5 != 0) {
            tongSoTrang += 1;
        }
        if (sotrang == 1) {
            fillToTable(cv2);
        } else {
            cv2.removeAll(cv2);
            sotrang -= 1;
            int heso = (sotrang * 5) - 5;
            cv2 = chucVuu.getAll2(heso);
            fillToTable(cv2);
            lblsotrang.setText(String.valueOf(sotrang) + "/" + tongSoTrang);
        }
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        int tongSoTrang = cv.size() / 5;
        if (cv.size() % 5 != 0) {
            tongSoTrang += 1;
        }
        if (sotrang == tongSoTrang) {
            fillToTable(cv2);
        } else {
            cv2.removeAll(cv2);
            sotrang += 1;
            int heso = (sotrang * 5) - 5;
            cv2 = chucVuu.getAll2(heso);
            fillToTable(cv2);
            lblsotrang.setText(String.valueOf(sotrang) + "/" + tongSoTrang);
        }

    }//GEN-LAST:event_btnnextActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
        int tongSoTrang = cv.size() / 5;
        if (cv.size() % 5 != 0) {
            tongSoTrang += 1;
        }
        cv2.removeAll(cv2);
        sotrang = tongSoTrang;
        int heso = (sotrang * 5) - 5;
        cv2 = chucVuu.getAll2(heso);
        fillToTable(cv2);
        lblsotrang.setText(String.valueOf(sotrang) + "/" + tongSoTrang);
    }//GEN-LAST:event_btnlastActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewNV_ChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewNV_ChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewNV_ChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewNV_ChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewNV_ChucVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnfirst;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnnext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblsotrang;
    private javax.swing.JTable tblchucvu;
    private edu.poly.duan1.swing.textfield.TextField txtsearch;
    // End of variables declaration//GEN-END:variables

    private void fillToTable() {
        tblModel = (DefaultTableModel) tblchucvu.getModel();
        tblModel.setRowCount(0);
        for (ChucVu x : chucVuu.getAll()) {
            tblModel.addRow(new Object[]{
                x.getId(),
                x.getMa(),
                x.getTen(),
//                sdf.format(x.getNgayTao()),
//                sdf.format(x.getNgaySua()),
                x.getTrangThai() == 1 ? "Còn Hoạt Động" : "Đã Nghỉ"});
        }

    }

    private void fillToTable(List<ChucVu> list) {
        tblModel = (DefaultTableModel) tblchucvu.getModel();
        tblModel.setRowCount(0);
        for (edu.poly.duan1.model.ChucVu x : list) {
            tblModel.addRow(new Object[]{
                x.getId(),
                x.getMa(),
                x.getTen(),
//                sdf.format(x.getNgayTao()),
//                sdf.format(x.getNgaySua()),
                x.getTrangThai() == 1 ? "Còn Hoạt Động" : "Đã Nghỉ"});
        }
    }

    public void search() {
        String ten = txtsearch.getText();
        if (ten.isEmpty()) {
            fillToTable(cv2);
        }else{
            fillToTable(chucVuu.search(ten));
        }

    }

    private void uppanel() {
        int tongsotrang = cv.size() / 5;
        if (cv.size() % 5 != 0) {
            tongsotrang += 1;

        }
        lblsotrang.setText(String.valueOf(sotrang) + "/" + tongsotrang);
    }
//    private void fill(){
//        cv = chucVuu.getAll();
//        int heso = (sotrang * 5) - 5;
//        cv2 = chucVuu.getAll2(heso);
//        fillToTable(cv2);
////        fillToTable();
//        uppanel();
//    }
}
