/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.poly.duan1.view;

import edu.poly.duan1.model.HoaDon;
import edu.poly.duan1.model.HoaDonCT;
import edu.poly.duan1.model.NguoiDung;
import edu.poly.duan1.model.Sach;
import edu.poly.duan1.model.thongke;
import edu.poly.duan1.repositories.HoaDonCTRepositories;
import edu.poly.duan1.services.HoaDonCTService;
import edu.poly.duan1.services.HoaDonService;
import edu.poly.duan1.services.SachServices;
import edu.poly.duan1.services.ThongKeService;
import edu.poly.duan1.services.impl.HoaDonCTServiceImpl;
import edu.poly.duan1.services.impl.HoaDonServiceImpl;
import edu.poly.duan1.services.impl.SachServicesImpl;
import edu.poly.duan1.services.impl.ThongKeServiceImpl;
import edu.poly.duan1.ultis.helper;
import edu.poly.main.Main;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Nguyen Thi Thu Thao
 */
public class View_ThongKe extends javax.swing.JFrame {

    private HoaDonCTService hoaDonCTService = new HoaDonCTServiceImpl();
    private ThongKeService thongKeService = new ThongKeServiceImpl();
    private HoaDonService hoaDonService = new HoaDonServiceImpl();
    private SachServices sachService = new SachServicesImpl();
    private DefaultTableModel tblModel;
    private helper helper = new helper();
    List<HoaDonCT> listHĐCT;
    List<thongke> listTK;
    List<HoaDon> listHĐ;
    private DefaultComboBoxModel<HoaDonCT> dcbmHoaDon;

    /**
     * Creates new form View_ThongKe
     */
    private NguoiDung nguoiDung = new NguoiDung();
    public View_ThongKe(NguoiDung nd) {
        initComponents();
        loadDataTableDoanhThu();
        this.setLocationRelativeTo(null);
        loadDataTableSanPham();
        this.nguoiDung = nd;
        Image icon = Toolkit.getDefaultToolkit().getImage("images/logo.png");
        this.setIconImage(icon);
    }
    public View_ThongKe() {
        initComponents();
        loadDataTableDoanhThu();
        this.setLocationRelativeTo(null);
        loadDataTableSanPham();
        Image icon = Toolkit.getDefaultToolkit().getImage("images/logo.png");
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKeDT = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongKeSP = new javax.swing.JTable();
        btnBieuDoSP = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongKeHoaDon = new javax.swing.JTable();
        btnTroVe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Thống kê");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm theo ngày", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnTimKiem))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tblThongKeDT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Năm", "Tháng", "Sản phẩm bán", "Doanh thu", "Lợi nhuận"
            }
        ));
        jScrollPane1.setViewportView(tblThongKeDT);

        jButton1.setText("Biểu đồ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(116, 116, 116))
        );

        jTabbedPane1.addTab("Doanh thu", jPanel3);

        tblThongKeSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Sản phẩm", "Tên sản phẩm", "Số lượng bán"
            }
        ));
        jScrollPane2.setViewportView(tblThongKeSP);

        btnBieuDoSP.setText("Biểu đồ");
        btnBieuDoSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBieuDoSPActionPerformed(evt);
            }
        });

        jButton2.setText("Xuất file");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBieuDoSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnBieuDoSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sản phẩm", jPanel4);

        tblThongKeHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Số lượng bán", "Đơn giá", "Tổng tiền"
            }
        ));
        jScrollPane3.setViewportView(tblThongKeHoaDon);

        btnTroVe.setText("trở về");
        btnTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTroVe)
                        .addGap(52, 52, 52))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnTroVe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        loadDataTableTheongay();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setDataToChart1();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBieuDoSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBieuDoSPActionPerformed
        setDataToChart2();
    }//GEN-LAST:event_btnBieuDoSPActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        writeExcel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeActionPerformed
        new Main(nguoiDung).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTroVeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_ThongKe().setVisible(true);

            }
        });
    }

    private void loadDataTableTheongay() {
        tblModel = (DefaultTableModel) tblThongKeHoaDon.getModel();
        tblModel.setRowCount(0);
        String date = txtTimKiem.getText();
        try {
            Date date1 = new SimpleDateFormat("dd/MM/yyyy").parse(date);
            if (date.length() > 0) {
                listTK = thongKeService.getHoadon(date1);
                for (thongke x : listTK) {
                    tblModel.addRow(new Object[]{
                        x.getTen(),
                        x.getSoLuong(),
                        x.getDongia(),
                        x.getDoanhThu()}
                    );
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(View_ThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadDataTableDoanhThu() {
        tblModel = (DefaultTableModel) tblThongKeDT.getModel();
        tblModel.setRowCount(0);
        for (thongke x : thongKeService.getList()) {
            tblModel.addRow(new Object[]{
                x.getNam(),
                x.getThang(),
                x.getSoLuong(),
                x.getDoanhThu(),
                x.getLoinhuan()}
            );
        }
    }

    private void loadDataTableSanPham() {
        tblModel = (DefaultTableModel) tblThongKeSP.getModel();
        tblModel.setRowCount(0);
        for (thongke x : thongKeService.getSanPham()) {
            tblModel.addRow(new Object[]{
                x.getMa(),
                x.getTen(),
                x.getSoLuong()}
            );
        }
    }

//    private void Tong() {
//        DecimalFormat x = new DecimalFormat("###,###,###");
//        int tong = 0;
//        for (int i = 0; i < tblThongKeDT.getRowCount(); i++) {
//            tong += Double.parseDouble(tblThongKeDT.getValueAt(i, 3).toString());
//        }
//        lbTongDoanhThu.setText(x.format(tong) + " " + "VNĐ");
//    }
    private CategoryDataset createDataset() {
        List<thongke> listItem = thongKeService.getDoanhThu();
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        if (listItem != null) {
            for (int i = 0; i < listItem.size(); i++) {
                dataset.addValue(listItem.get(i).getDoanhThu(), "Doanh thu", listItem.get(i).getNam());
            }
        }
        return dataset;
    }

    private CategoryDataset createDataset1() {
        List<thongke> listItem = thongKeService.getBieuDoSanPham();
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        if (listItem != null) {
            for (int i = 0; i < listItem.size(); i++) {
                dataset.addValue(listItem.get(i).getSoLuong(), "Sản phẩm", listItem.get(i).getTen());
            }
        }
        return dataset;
    }

    public JFreeChart createChart1() {
        JFreeChart barChart = ChartFactory.createBarChart(
                "Biểu đồ thống kê sản phẩm đã bán".toUpperCase(),
                "Sản phẩm", "Số lượng",
                createDataset1(), PlotOrientation.VERTICAL, false, true, false);
        return barChart;
    }

    public JFreeChart createChart() {
        JFreeChart barChart = ChartFactory.createBarChart(
                "Biểu đồ thống kê doanh thu từng năm".toUpperCase(),
                "Thời gian", "Doanh thu",
                createDataset(), PlotOrientation.VERTICAL, false, true, false);
        return barChart;
    }

    public void setDataToChart2() {
        ChartPanel chartPanel = new ChartPanel(createChart1());
        chartPanel.setPreferredSize(new Dimension((new java.awt.Dimension(100, 100))));
        JFrame frame = new JFrame();
        frame.add(chartPanel);
        frame.setTitle("Biểu đồ thống kê");
        frame.setSize(600, 400);
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
        frame.setVisible(true);
//        pnlBieuDo.removeAll();
//        pnlBieuDo.add(chartPanel);
    }

    public void setDataToChart1() {
        ChartPanel chartPanel = new ChartPanel(createChart());
        chartPanel.setPreferredSize(new Dimension((new java.awt.Dimension(100, 100))));
        JFrame frame = new JFrame();
        frame.add(chartPanel);
        frame.setTitle("Biểu đồ thống kê");
        frame.setSize(600, 400);
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
        frame.setVisible(true);
//        pnlBieuDo.removeAll();
//        pnlBieuDo.add(chartPanel);
    }

    public void writeExcel() {
        try {
            SimpleDateFormat dateTimeFM = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            listTK = thongKeService.getExcel();
            String date = dateTimeFM.format(new Date());
            String i = UUID.randomUUID().toString();
            String a = i.substring(0, 4);
            FileOutputStream file = new FileOutputStream("C:\\Users\\quank\\OneDrive\\Desktop\\thongke" + a + ".xlsx");
            XSSFWorkbook worbook = new XSSFWorkbook();
            XSSFSheet worksheet = worbook.createSheet("Thống Kê Sản Phẩm");
            XSSFRow row;
            XSSFCell ma, ten, soluong, soluonton;
            int i1 = 1;
            row = worksheet.createRow(i1);
            ma = row.createCell(0);
            ma.setCellValue("Mã Sản Phẩm");
            ten = row.createCell(1);
            ten.setCellValue("Tên Sản Phẩm");
            soluong = row.createCell(2);
            soluong.setCellValue("Số Lượng Bán");
            soluonton = row.createCell(3);
            soluonton.setCellValue("Số Lượng Còn");
            for (thongke t : listTK) {
                i1++;
                Sach sp = sachService.getObjbyMa(t.getMa());
                row = worksheet.createRow(i1);
                ma = row.createCell(0);
                ma.setCellValue(t.getMa());
                ten = row.createCell(1);
                ten.setCellValue(t.getTen());
                soluong = row.createCell(2);
                soluong.setCellValue(t.getSoLuong());
                soluonton = row.createCell(3);
                soluonton.setCellValue(t.getSoluonton());
            }
            worbook.write(file);
            worbook.close();
            file.close();
            JOptionPane.showMessageDialog(this, "Xuất báo cáo thành công");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBieuDoSP;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTroVe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblThongKeDT;
    private javax.swing.JTable tblThongKeHoaDon;
    private javax.swing.JTable tblThongKeSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
