/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.poly.duan1.view;

import edu.poly.duan1.model.NguoiDung;
import edu.poly.duan1.repositories.NguoiDungRepositories;
import edu.poly.duan1.services.NguoiDungService;
import edu.poly.duan1.services.impl.NguoiDungServiceImpl;
import edu.poly.duan1.ultis.MailSender;
import edu.poly.duan1.ultis.helper;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.UUID;

/**
 *
 * @author ADMIN
 */
public class view_QuenMK extends javax.swing.JFrame {

    /**
     * Creates new form view_QuenMK
     */
    helper helper = new helper();
    String ma = UUID.randomUUID().toString().substring(0, 6);
    MailSender sendMail = new MailSender();
    private NguoiDungService nguoiDungSer = new NguoiDungServiceImpl();

    public view_QuenMK() {
        initComponents();

        lblTitel.setText("Mã xác minh");
        lblMa.setText(ma);
        setLocationRelativeTo(null);
     Image icon = Toolkit.getDefaultToolkit().getImage("images/logo.png");
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmail = new edu.poly.duan1.swing.textfield.TextField();
        button1 = new edu.poly.duan1.swing.button.Button();
        btnGuiMK = new edu.poly.duan1.swing.button.Button();
        jLabel1 = new javax.swing.JLabel();
        txtMa = new edu.poly.duan1.swing.textfield.TextField();
        pnXacMinh = new javax.swing.JPanel();
        lblTitel = new javax.swing.JLabel();
        lblMa = new javax.swing.JLabel();
        lblReset = new javax.swing.JLabel();
        txtUser = new edu.poly.duan1.swing.textfield.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtEmail.setLabelText("Email");

        button1.setBackground(new java.awt.Color(3, 155, 216));
        button1.setText("Trở về");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        btnGuiMK.setBackground(new java.awt.Color(3, 155, 216));
        btnGuiMK.setText("Gửi Mật Khẩu");
        btnGuiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiMKActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(3, 155, 216));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOK STORE LOGIN");

        txtMa.setLabelText("Mã xác minh");

        pnXacMinh.setBackground(new java.awt.Color(255, 255, 255));

        lblTitel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitel.setText("abc");

        lblMa.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblMa.setForeground(new java.awt.Color(3, 155, 216));
        lblMa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMa.setText("aaa");

        javax.swing.GroupLayout pnXacMinhLayout = new javax.swing.GroupLayout(pnXacMinh);
        pnXacMinh.setLayout(pnXacMinhLayout);
        pnXacMinhLayout.setHorizontalGroup(
            pnXacMinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXacMinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnXacMinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMa, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(lblTitel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnXacMinhLayout.setVerticalGroup(
            pnXacMinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXacMinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset.png"))); // NOI18N
        lblReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblResetMousePressed(evt);
            }
        });

        txtUser.setLabelText("Tài Khoản");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnXacMinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(lblReset))
                            .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEmail, txtMa, txtUser});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnGuiMK, button1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnXacMinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblReset)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuiMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEmail, txtMa, txtUser});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnGuiMK, button1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblResetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMousePressed
        ma = UUID.randomUUID().toString().substring(0, 6);
        lblMa.setText(ma);
    }//GEN-LAST:event_lblResetMousePressed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        if (helper.confirm(this, "Bạn có muốn chuyển qua màn hình đăng nhập không?")) {
            this.dispose();
            new view_DangNhap().setVisible(true);
        }
    }//GEN-LAST:event_button1ActionPerformed
    private void taoMa() {
        ma = UUID.randomUUID().toString().substring(0, 6);
        lblMa.setText(ma);
    }
    private void btnGuiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiMKActionPerformed
        if (CheckNull()) {
            String email = txtEmail.getText();
            NguoiDung nd = nguoiDungSer.getObjbyMa(txtUser.getText());
            if (!txtMa.getText().equals(lblMa.getText())) {
                helper.error(this, "Mã xác minh không đúng vui lòng nhập lại");
                taoMa();
            } else if (nd == null) {
                helper.error(this, "Người dùng không tồn tại!");
                taoMa();
            } else if (!email.equals(nguoiDungSer.getObjbyMa(txtUser.getText()).getEmail())) {
                helper.error(this, "Email không tồn tại!");
                taoMa();
            } else {
                String mk = UUID.randomUUID().toString().substring(0, 6).toUpperCase();
                nd.setMatKhau(mk);

                nguoiDungSer.saveOrUpdate(nd);

                sendMail.MailSender(email, mk);
                helper.alert(this, "Mật khẩu mới đã được gửi đến email của bạn");
            }
        }
    }//GEN-LAST:event_btnGuiMKActionPerformed
    private Boolean CheckNull() {
        if (helper.checkNull(txtMa, "Mã xác minh không được để trống")
                || helper.checkNull(txtEmail, "Email không được để trống")
                || helper.checkNull(txtUser, "Tài khoản không được để trống")) {

            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_QuenMK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.poly.duan1.swing.button.Button btnGuiMK;
    private edu.poly.duan1.swing.button.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblReset;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JPanel pnXacMinh;
    private edu.poly.duan1.swing.textfield.TextField txtEmail;
    private edu.poly.duan1.swing.textfield.TextField txtMa;
    private edu.poly.duan1.swing.textfield.TextField txtUser;
    // End of variables declaration//GEN-END:variables
}
